name = "EarthMoversDistance"
uuid = "e1737d0f-dfce-5227-9318-d7961fac91f7"
authors = ["Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
